Default: &defaults
  database: Avasys.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Avasys_test.sqlite3
  <<: *defaults

Staging:
  database: Avasys_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Avasys_production.sqlite3
  poolsize: 100
  <<: *defaults
